### PR TITLE
feat: use new nft.storage client for uploading

### PR DESCRIPTION
**Pull request by yusefnapora**
This replaces all the custom car packing / chunking / uploading code with the standard nft.storage client, with the `NFTStorage.auth` method overridden to set our custom `x-web3auth` header instead of the `Authorization` header.

I still need to test this end-to-end as I got sidetracked today, but it's much nicer this way :)

Will try to test and merge tomorrow.

### CODE REVIEW

**Comment by kevinfaveri** [comment]
Hey @yusefnapora! Is this ready? Looks like a way better API :)

**Comment by yusefnapora** [comment]
Sadly there's a blocker to merging this that needs to be sorted out in the nft.storage client - basically my hack of tricking the client into using `/metaplex/upload` instead of the `/upload` it wants to use for `putCar` doesn't work, since the entire path portion of the endpoint URL is replaced. 

I wrote this assuming that the would just append `/upload` to the end of whatever endpoint URL you give it, but I should have tested that assumption first 😄

@alanshaw do you think we could modify the client's `putCar` method so that we can selectively target the metaplex endpoint? I meant to ask you about this a few days ago but got caught up in the weeds of getting uploads working on staging, etc.

**Comment by yusefnapora** [comment]
It seems that wasn't a blocker after all, and I just needed a trailing slash character on my url prefix :) (thanks @alanshaw).

I'll clean this PR up and aim to merge today, and update the metaplex PR to use it.

**Comment by yusefnapora** [comment]
@kevinfaveri I'm going to go ahead and merge this, but it may take a few hours before I'll be ready to publish a new version to npm. If you're around and want to play with it before then, you can target `main` temporarily.

**Pull request merged**
