### PR TITLE
feat: add ability to bundle many NFTs into one CAR for upload

### PR DESCRIPTION
**Pull request by yusefnapora**
This adds an `NFTBundle` class that uses one Blockstore instance to pack multiple NFTs by threading it through the `NFTStorage.encode*` methods. The idea is to improve the performance of candy machine uploads by making one big CAR for all the NFTs in your collection, which will cut down on round trips and lets the client parallelize things.

Once you've added all your NFTs to an `NFTBundle`, you can call `bundle.asCAR()`, which spits out a CAR with all the blocks you've imported, plus a "manifest" dag-cbor object at the root that links to each NFT.  I added the manifest block since I think we require uploaded CARs to have a single root CID.

Opening as a draft since there's still things to do:

- [x] tests!
- [X] add a method to get the metadata URLs for each NFT in the bundle
  - can either path through the root block or use the URLs returned from the add to bundle methods
- [x] add a helper to slurp up a directory full of NFTs
- [x] make sure schema validation is up to date, or disable entirely

### CODE REVIEW

**Comment by yusefnapora** [comment]
Feels like this is headed in a good direction. I'm going to start focusing on integrating this with the candy machine cli, on the assumption that I might want to change the API a bit once I use it.

**Comment by yusefnapora** [comment]
I've got this integrated into a branch, and it seems to work well. I could use a quick sanity check to make sure I'm not re-inventing any wheels here... maybe @alanshaw or @Gozala could take a look.

Basically, this lib has a few methods for loading NFTs that eventually call through to `NFTStorage.encodeDirectory`, resulting in two `CarReader`s - one for a dir with all the assets, and one for a directory with a `metadata.json` inside.

This PR adds an `NFTBundle` class that calls through to the various `loadNFT` methods, passing in a single shared `Blockstore` instance. Then it lets you generate a `CarReader` containing all the blocks from the shared blockstore, plus a "manifest" wrapper object that links to the roots of each bundled CAR.

Essentially, the `NFTBundle` is just a "staging area" that makes it a little easier to build up a CAR that's composed of multiple outputs of `encodeDirectory` (or `encode*`). 

My questions are: do we already have something like this that I should be using instead? 

Also, I didn't really put a lot of thought into the "manifest" root object; it has an `nfts` array with objects that link to the `assets` and `metadata` directory objects for each loaded NFT. There's nothing on the metaplex / candy machine side that cares about the manifest object's shape - it's just there so we have a complete graph with a single root CID. 

So maybe the shape of the object doesn't matter. We could make it even more generic though, and just have an array of CIDs instead of separate `assets` and `metadata` links.

**Comment by alanshaw** [comment]
The only issue with a manifest CBOR node at the root is that you need to ensure it doesn't grow larger than 1MB to ensure IPFS can bitswap it.

I'm also not sure how pathing works via gateway from the root CBOR node with an array - I assume something like: `<cid>/nfts/0/assets/...`.

It might be better to create a HAMT sharded unixfs directory for the root node since this is understood by the gateway (as in you don't need to path through shards) and would keep the root node in the size limit. However I don't know if there's any libraries available to do that yet (I _think_ @Gozala's new unixfs importer _will_, but it's not finished).

**Comment by yusefnapora** [comment]
That's a really good point about the size limit.

I like the idea of using a directory, since it would be nice to be able to path through the bundle using the gateway. I'll have a go at a dag-pb implementation and add a check to make sure it doesn't exceed the shard size limit. On the candy machine side, I've set the default batch size to 50 NFTs, so most people probably won't end up with more than 100 or so entries in the root block. But I'd rather explicitly fail if they do hit the limit, rather than make a CAR that nobody can use.

**Comment by yusefnapora** [comment]
Last few commits implement the dag-pb root block, with a limit of 5000 NFTs per bundle, which results in a root block size of about 240kb. Since the entries are a constant size, it seems simplest to just set a limit on number of entries instead of computing the actual size all the time.

Here's a few bundle root objects from a test run with 5 nfts, with the `batchSize` set to 2 so it got split into 3 bundles:

- https://bafybeieqcmqcnku3s3vaxjjfmdz6ppdz735ohr62xtlfadjmy257cc5q2i.ipfs.nftstorage.link/
- https://bafybeifxpd77x3rub4dfgw4ozhcxi6ajqwl3gp3oxsvpaw2movmfiwpri4.ipfs.nftstorage.link/
- https://bafybeibqafcb3nclh7ovjebx4zjnfgszlyr2orbunlv3c2q6zbuiq4w4ly.ipfs.nftstorage.link/

I tweaked the addNFT methods a bit to require a unique `id` string for each added nft, to use as the name for links from the root object. You end up with paths like `<id>/assets/foo.png` and `<id>/metadata/metadata.json`.

I also ended up removing the `addAllNFTsFromDirectory` method, since it seemed too finicky to guarantee unique ids, and I'm not using it on the candy machine side anyway.

**Comment by yusefnapora** [comment]
Just did a comparison of my metaplex fork using this branch to the current serial upload in metaplex `master`. Good news!  It's about 1.5x faster now :)

Using this branch, it took about 20m to run `candy-machine upload` on a collection of 500 NFTs (using pics from thiscatdoesnotexist.com). The code on `master` took almost 45m, and 8 of the NFTs failed to upload due to rate limit errors. It seems likely that there are more rate limit errors being hidden by automatic retry logic in the client, which would explain why the time difference is so dramatic.

I'll run another round tomorrow from a VM with less variable upload speed - mine is less awful than it used to be, but it's still kind of erratic, so it's not really a fair benchmark.

Also I realized that my earlier comment about the entries in the root block all being the same size isn't quite right - since you can use any string as the id (which gets used as the directory / link name), the size depends on user input. I'll probably lower the MAX_ENTRIES a bit and add a max length for the id string, just in case.

Anyway, I'll aim to release this package tomorrow afternoonish and make the candy machine PR - @alanshaw let me know if you think there's anything I ought to tweak first.

**Comment by yusefnapora** [comment]
Did another test with the same collection, but from a digital ocean droplet instead of my janky home connection.

The bundled upload completed in 12m25s, but the serial upload in metaplex `master` took 38m25s and again had some upload failures due to rate limiting. So it seems like on a decent connection the difference is even more dramatic, with bundles clocking in at about 3x faster than the current implementation.

**Comment by yusefnapora** [comment]
This seems good enough to be getting on with, so I'm going to pull it in :) 

Hopefully we can get a sharded root block happening at some point, but I don't think it's likely to matter for the candy machine use case. Even if you're uploading more than the 2.2K NFTs that will fit in a single bundle, you probably want to split into smaller batches that that, since each bundle gets cached as a group, and will be retried as a group if things fail. So even for huge drops you probably wouldn't want more than 1K or so entries per bundle.

**Pull request merged**
